# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FinalWork_JanyErtveldt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FinalWork_JanyErtveldt

  target 'FinalWork_JanyErtveldtTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FinalWork_JanyErtveldtUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Firebase/Core'
pod 'Firebase/Database'

end
